[[redirects]]
  from = "/api/qr/login/*"
  to = "https://qr.arkagme.biz/api/qr/login/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/qr/*"
  to = "https://qr.arkagme.biz/api/qr/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}


[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  conditions = {Pathname = ["!^/api/*", "!^/oauth2/*"]}
