[[redirects]]
  from = "/login/federated/google"
  to = "https://qr.arkagme.biz/login/federated/google"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/api/*"
  to = "https://qr.arkagme.biz/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  # Explicitly exclude API paths from client-side routing
  conditions = {Pathname = ["!^/api/*", "!^/oauth2/*"]}
