[[redirects]]
  from = "/oauth2/redirect/google"  # Explicit path first
  to = "https://qr.arkagme.biz/oauth2/redirect/google"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/api/*"
  to = "https://qr.arkagme.biz/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}

[[redirects]]  # Client-side routing LAST
  from = "/*"
  to = "/"
  status = 200
